# -*- coding: utf-8 -*-
"""Web_scraper_ŠŠ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TiRY-ktE7QbDoxFcvkbYRWywJ16NPTFT
"""

"""
final_projekt.py: finalní projekt – scraper voleb 2017
author: Bagster
email: simon@unknown.com
"""

import sys
import requests
from bs4 import BeautifulSoup
import csv


def zkontroluj_argumenty():
    """Funguje v Colab i terminálu"""
    try:
        url = sys.argv[1]
        vystup = sys.argv[2]

        if "volby.cz" not in url or not vystup.endswith(".csv"):
            raise ValueError

    except (IndexError, ValueError):
        print(" Colab režim → používám testovací hodnoty")
        url = "https://www.volby.cz/pls/ps2017nss/ps32?xjazyk=CZ&xkraj=2&xnumnuts=2101"
        vystup = "vysledky.csv"

    return url, vystup


def stahni_stranku(url):
    try:
        response = requests.get(url)
        response.raise_for_status()
        return response.text
    except requests.exceptions.RequestException as e:
        raise ConnectionError(f"Chyba při stahování stránky: {e}")


def ziskej_obce(html):
    """Získá seznam obcí (SPRÁVNĚ přes ps311)"""
    soup = BeautifulSoup(html, "html.parser")
    obce = []

    for row in soup.find_all("tr"):
        cols = row.find_all("td")

        if len(cols) >= 3:
            odkaz = cols[0].find("a")

            if odkaz and "ps311" in odkaz.get("href", ""):
                kod = cols[0].text.strip()
                nazev = cols[1].text.strip()
                link = "https://www.volby.cz/pls/ps2017nss/" + odkaz["href"]

                obce.append((kod, nazev, link))

    if not obce:
        raise ValueError("Nepodařilo se najít žádné obce.")

    return obce


def zpracuj_obec(url):
    """Získá detail obce"""
    html = stahni_stranku(url)
    soup = BeautifulSoup(html, "html.parser")

    try:
        volici = soup.find("td", headers="sa2").text.strip()
        obalky = soup.find("td", headers="sa3").text.strip()
        platne = soup.find("td", headers="sa6").text.strip()
    except AttributeError:
        raise ValueError("Nepodařilo se načíst statistiky obce.")

    strany = []
    hlasy = []

    tables = soup.find_all("table")

    for table in tables:
        rows = table.find_all("tr")[2:]

        for row in rows:
            cols = row.find_all("td")

            if len(cols) >= 3:
                strany.append(cols[1].text.strip())
                hlasy.append(cols[2].text.strip())

    return volici, obalky, platne, strany, hlasy


def uloz_csv(soubor, data, hlavicka):
    try:
        with open(soubor, mode="w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(hlavicka)
            writer.writerows(data)
    except IOError as e:
        raise IOError(f"Chyba při zápisu do souboru: {e}")


def main():
    try:
        url, vystup = zkontroluj_argumenty()

        print(f" Stahuji: {url}")

        html = stahni_stranku(url)
        obce = ziskej_obce(html)

        vysledky = []
        hlavicka = ["kód obce", "název obce", "voliči", "obálky", "platné hlasy"]

        # získání názvů stran z první obce
        _, _, _, strany, _ = zpracuj_obec(obce[0][2])
        hlavicka.extend(strany)

        for kod, nazev, link in obce:
            print(f" Zpracovávám: {nazev}")

            volici, obalky, platne, _, hlasy = zpracuj_obec(link)

            radek = [kod, nazev, volici, obalky, platne] + hlasy
            vysledky.append(radek)

        uloz_csv(vystup, vysledky, hlavicka)

        print(f"\n Hotovo! Uloženo jako: {vystup}")

    except Exception as e:
        print(f"\n Chyba: {e}")
        return


if __name__ == "__main__":
    main()